name: Checking code coverage

on: [push, pull_request]

jobs:
  check_coverage:
    name: Check coverage
    runs-on: ubuntu-latest

    env:
      OS: ubuntu-latest
      PYTHON: 3.9

    steps:
    - name: Checkout mothra
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9

    - name: Generate Report
      run: |
        pip install coverage pytest
        pip install -r requirements.txt
        PYTHONPATH=. coverage run -m pytest
        coverage report -m  # showing coverage output
        coverage xml  # generates file needed for CodeCov

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
